# **Homework 1**

## Import packages

In [39]:
import numpy as np
import pandas as pd

Get Pandas version

In [40]:
pd.__version__

'2.3.3'

## Load data

In [41]:
df = pd.read_csv("data/car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


Data shape

In [43]:
df.shape

(9704, 11)

Number of fuel types

In [44]:
df['fuel_type'].nunique()

2

Number of columns with missing values

In [45]:
df.isna().any().sum()

np.int64(4)

Maximum fuel efficiency of cars from Asia?

In [46]:
# Get unique origins
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [47]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

Median value of horsepower

In [48]:
# Median before missing value imputation
median_before_imputation = df['horsepower'].median()
median_before_imputation

np.float64(149.0)

In [49]:
# Most frequent value of horsepower
most_frequent_horsepower = df['horsepower'].mode()[0]
most_frequent_horsepower

np.float64(152.0)

In [50]:
# Impute missing values in horsepower with most_frequent_horsepower
df['horsepower'] = df['horsepower'].fillna(most_frequent_horsepower)

In [51]:
# Median after missing value imputation
median_after_imputation = df['horsepower'].median()
median_after_imputation

np.float64(152.0)

Sum of weights

In [52]:
# Asian cars
asian_cars = df[df['origin'] == 'Asia']
asian_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [53]:
# Asian cars' vehicle_weight and model_year

asian_cars_select =  asian_cars[['vehicle_weight', 'model_year']]
asian_cars_select = asian_cars_select.head(7)
asian_cars_select

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [54]:
# Turn asian_car_select into a NumPy array
X = asian_cars_select.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [55]:
# Matrix-matrix multiplication between the transpose of X and X
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [56]:
# Array y
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [57]:
# Compute w
m = np.linalg.inv(XTX) @ X.T
w = m @ y
w

array([0.01386421, 0.5049067 ])

In [58]:
# Sum of all the elements of w
sum_w = w.sum()
sum_w

np.float64(0.5187709081074016)